const EmployeeInterface = {
  id: null,
  image: '',
  first_name: '',
  second_name: '',
  surname: '',
  second_surname: '',
  company_id: null,
  branch_office_id: null,
  warehouse_id: null,
  document_type: null,
  avatar_id: null,
  avatars: {},
  work_area_id: null,
  work_areas: {},
  job_position_id: null,
  job_positions: {},
  document_number: '',
  email: '',
  phone: '',
  birthdate: null,
  gender: 0,
  status: 1,
}

export default EmployeeInterface